In [56]:
!pip install numpy

Import numpy first

In [57]:
import numpy as np

Create 1D array using numpy

In [58]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


1D array using Reshaping

In [59]:
arr2=np.array([1,2,3,4,5,6,7]) # manually (arr2=np.array([[1,2,3,4,5,6,7]])
arr2=arr2.reshape(1,7) # 1 row and 7 columns
print(arr2.shape)

(1, 7)


2D Array

In [60]:
arr3=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


# Functions

In [61]:
arr=np.arange(0,10,2).reshape(5,1)
print(arr)


[[0]
 [2]
 [4]
 [6]
 [8]]


In [62]:
arr=np.ones((3,4)) #create a n x m dim array on 1's
print(arr.shape)
print(arr)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Identity Matrix

In [63]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Attributes of Numpy Array

In [64]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of Dimension:",arr.ndim)
print("Size (Number of Elements):",arr.size)
print("Data Type:",arr.dtype) #May vary depend on platform
print("Item Size (in Bytes):",arr.itemsize)

Array:
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape: (2, 5)
Number of Dimension: 2
Size (Number of Elements): 10
Data Type: int64
Item Size (in Bytes): 8


# Numpy Vectorized Operation

In [65]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

element wise addition

In [66]:
arr3=arr1+arr2
print(arr3)
print(type(arr3))

[11 22 33 44 55]
<class 'numpy.ndarray'>


element wise subtraction

In [67]:
arr3=arr1-arr2
print(arr3)
print(type(arr3))

[ -9 -18 -27 -36 -45]
<class 'numpy.ndarray'>


element wise multiplication

In [68]:
arr3=arr1*arr2
print(arr3)
print(type(arr3))

[ 10  40  90 160 250]
<class 'numpy.ndarray'>


element wise division

In [69]:
arr3=arr1/arr2
print(arr3)
print(type(arr3))

[0.1 0.1 0.1 0.1 0.1]
<class 'numpy.ndarray'>


element wise mod

In [70]:
arr3=arr1%arr2
print(arr3)
print(type(arr3))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Universal Function

In [71]:
arr=np.array([2,3,4,5,6])

Square root

In [72]:
arr4=np.sqrt(arr)
print(arr4)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


exponential

In [73]:
arr4=np.exp(arr)
print(arr4)

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


Sine

In [74]:
arr4=np.sin(arr)
print(arr4)

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


Natural log

In [75]:
arr4=np.log(arr)
print(arr4)

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


# Array Slicing and Indexing

In [76]:
arr=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [77]:
print("Array:\n",arr)

Array:
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [78]:
print(arr[1][0])

2


In [79]:
print(arr[1:,2:])

[[4 5]
 [5 6]]


In [80]:
print(arr[0:2,2:])

[[3 4]
 [4 5]]


In [81]:
print(arr[0:2,1:3])

[[2 3]
 [3 4]]


# Modify Array Elements

In [82]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  2   3   4   5]
 [  3   4   5   6]]


In [83]:
arr[1,0]=200
print(arr)

[[100   2   3   4]
 [200   3   4   5]
 [  3   4   5   6]]


In [84]:
arr[2,0]=300
print(arr)

[[100   2   3   4]
 [200   3   4   5]
 [300   4   5   6]]


In [85]:
arr[0:,2:]=150
print(arr)

[[100   2 150 150]
 [200   3 150 150]
 [300   4 150 150]]


# Statistical Concept----- Normalization
to have a mean of 0 and standard daviation of 1

In [86]:
data= np.array([1,2,3,4,5])

#Calculate the mean
min=np.mean(data)

#Calculate the Standard Daviation
stdn=np.std(data)

#Normalize the Data
normalized_data= (data-min)/stdn

print("Normalized Data: ", normalized_data)


Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [87]:
arr=np.arange(0,10,1).reshape(2,5)
print(arr)

#Mean
print("Mean: ",np.mean(arr))

#Median
print("Median: ",np.median(arr))

#Standard Daviation
print("Standard Daviation: ",np.std(arr))

#Variance
print("Variance: ",np.var(arr))


[[0 1 2 3 4]
 [5 6 7 8 9]]
Mean:  4.5
Median:  4.5
Standard Daviation:  2.8722813232690143
Variance:  8.25


# Logical Operation

In [55]:
arr=np.arange(0,10,1)

print(arr>5)

print(arr[arr>5])

print(arr[(arr>=5) & (arr<=9)])

[False False False False False False  True  True  True  True]
[6 7 8 9]
[5 6 7 8 9]
