In [1]:
!pip install numpy

Import numpy first

In [2]:
import numpy as np

Create 1D array using numpy

In [5]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


1D array using Reshaping

In [ ]:
arr2=np.array([1,2,3,4,5,6,7]) # manually (arr2=np.array([[1,2,3,4,5,6,7]])
arr2=arr2.reshape(1,7) # 1 row and 7 columns
print(arr2.shape)

(1, 7)


2D Array

In [12]:
arr3=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


# Functions

In [66]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) #create a n x m dim array on 1's

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Identity Matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Attributes of Numpy Array

In [29]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of Dimension:",arr.ndim)
print("Size (Number of Elements):",arr.size)
print("Data Type:",arr.dtype) #May vary depend on platform
print("Item Size (in Bytes):",arr.itemsize)

Array:
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape: (2, 5)
Number of Dimension: 2
Size (Number of Elements): 10
Data Type: int64
Item Size (in Bytes): 8


# Numpy Vectorized Operation

In [32]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

element wise addition

In [34]:
arr3=arr1+arr2
print(arr3)
print(type(arr3))

[11 22 33 44 55]
<class 'numpy.ndarray'>


element wise subtraction

In [35]:
arr3=arr1-arr2
print(arr3)
print(type(arr3))

[ -9 -18 -27 -36 -45]
<class 'numpy.ndarray'>


element wise multiplication

In [36]:
arr3=arr1*arr2
print(arr3)
print(type(arr3))

[ 10  40  90 160 250]
<class 'numpy.ndarray'>


element wise division

In [37]:
arr3=arr1/arr2
print(arr3)
print(type(arr3))

[0.1 0.1 0.1 0.1 0.1]
<class 'numpy.ndarray'>


element wise mod

In [38]:
arr3=arr1%arr2
print(arr3)
print(type(arr3))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Universal Function

In [43]:
arr=np.array([2,3,4,5,6])

Square root

In [44]:
arr4=np.sqrt(arr)
print(arr4)

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


exponential

In [46]:
arr4=np.exp(arr)
print(arr4)

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


Sine

In [48]:
arr4=np.sin(arr)
print(arr4)

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


Natural log

In [50]:
arr4=np.log(arr)
print(arr4)

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


# Array Slicing and Indexing

In [51]:
arr=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [52]:
print("Array:\n",arr)

Array:
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [55]:
print(arr[1][0])

2


In [56]:
print(arr[1:,2:])

[[4 5]
 [5 6]]


In [59]:
print(arr[0:2,2:])

[[3 4]
 [4 5]]


In [61]:
print(arr[0:2,1:3])

[[2 3]
 [3 4]]


# Modify Array Elements

In [ ]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  2   3   4   5]
 [  3   4   5   6]]


In [63]:
arr[1,0]=200
print(arr)

[[100   2   3   4]
 [200   3   4   5]
 [  3   4   5   6]]


In [64]:
arr[2,0]=300
print(arr)

[[100   2   3   4]
 [200   3   4   5]
 [300   4   5   6]]
