In [3]:
import numpy as np

# You create a 2D array that stores marks for a number of students across different subjects.

Example:
Rows = Students,
Columns = Subjects,
So a 50×5 array means: 50 students,
5 subjects (e.g., Math, Physics, Chemistry, Biology, English)

In [5]:
# Generating Random Marks for Students
marks=np.random.randint(40,100, size=(50,5))
subjects=["Math", "Physics", "Chemistry", "Biology", "English"]
print(marks)

[[51 50 46 71 51]
 [60 95 42 57 57]
 [53 40 83 91 70]
 [98 47 62 44 94]
 [70 73 77 92 59]
 [98 46 82 92 57]
 [90 56 71 89 76]
 [48 88 54 57 82]
 [55 87 74 65 96]
 [85 86 41 89 88]
 [96 86 59 97 90]
 [56 77 84 83 71]
 [60 99 45 46 85]
 [77 65 69 42 62]
 [94 98 76 91 48]
 [91 79 92 62 65]
 [90 44 98 74 44]
 [59 99 85 80 86]
 [88 69 74 58 69]
 [72 58 43 48 53]
 [40 74 97 51 93]
 [78 46 77 72 49]
 [55 53 79 96 41]
 [90 73 86 47 92]
 [51 41 98 64 75]
 [64 50 57 65 63]
 [89 78 66 59 67]
 [57 49 55 50 82]
 [79 41 40 89 76]
 [54 73 77 82 55]
 [50 62 79 61 97]
 [56 46 58 76 59]
 [57 55 92 88 94]
 [89 85 60 49 64]
 [77 69 47 81 96]
 [60 95 87 78 87]
 [64 67 91 62 64]
 [79 96 86 61 68]
 [51 69 44 62 92]
 [95 49 58 99 64]
 [42 55 50 85 65]
 [74 53 50 93 97]
 [89 59 67 93 94]
 [49 86 81 70 50]
 [86 83 65 68 72]
 [97 45 47 93 54]
 [44 46 65 82 66]
 [68 45 77 91 61]
 [54 53 54 43 51]
 [91 72 95 90 95]]


# Performing Statistical Analysis
1. Average Marks per Student
2. Average Marks per Subject
3. Maximum and Minimum Marks per Subject
4. Standard Deviation for Each Subject

In [6]:
# 1. Average Marks per Student
avg_marks_per_student=np.mean(marks, axis=1)
print(avg_marks_per_student.reshape(50,1))

[[53.8]
 [62.2]
 [67.4]
 [69. ]
 [74.2]
 [75. ]
 [76.4]
 [65.8]
 [75.4]
 [77.8]
 [85.6]
 [74.2]
 [67. ]
 [63. ]
 [81.4]
 [77.8]
 [70. ]
 [81.8]
 [71.6]
 [54.8]
 [71. ]
 [64.4]
 [64.8]
 [77.6]
 [65.8]
 [59.8]
 [71.8]
 [58.6]
 [65. ]
 [68.2]
 [69.8]
 [59. ]
 [77.2]
 [69.4]
 [74. ]
 [81.4]
 [69.6]
 [78. ]
 [63.6]
 [73. ]
 [59.4]
 [73.4]
 [80.4]
 [67.2]
 [74.8]
 [67.2]
 [60.6]
 [68.4]
 [51. ]
 [88.6]]


In [7]:
# 2. Average Marks per Subject
avg_marks_per_subject=np.mean(marks, axis=0)
avg_marks_per_subject.reshape(1,5)
print(avg_marks_per_subject)

[70.4  66.2  68.84 72.56 71.72]


In [8]:
# 3. Maximum and Minimum Marks Per Subject

maximum=np.max(marks, axis=0)
minimum=np.min(marks, axis=0)
print("Maximum marks in each subject: ",maximum)
print("Minimum marks in each subject: ",minimum)

Maximum marks in each subject:  [98 99 98 99 97]
Minimum marks in each subject:  [40 40 40 42 41]


In [28]:
# 4. Standard Daviation for Each Subject
std_each_subject=np.std(marks, axis=0)
print("Standard Daviation for Each Subject: ",std_each_subject)

Standard Daviation for Each Subject:  [17.58577835 16.91744662 16.3682131  18.53541475 18.72115381]


# Identify Top and Bottom Students

What you're doing:
1. Find the student who has the highest overall average.
2. Find the student with the lowest overall average.

In [32]:
avg=np.mean(marks, axis=1)
avg.reshape(50,1)
top=np.argmax(avg)
print("Student with Highest Overall Score: ",top)
bottom=np.argmin(avg)
print("Student with Lowest Overall Score: ",bottom)

Student with Highest Overall Score:  16
Student with Lowest Overall Score:  10


# Identify Toppers per Subject

For each subject, find the student who got the highest score.

Then print:
1. Subject name
2. Student index
3. Mark obtained

In [35]:
subject_topper=np.argmax(marks, axis=0)
print(subject_topper)

for i,sub in enumerate(subjects):
    student_index=subject_topper[i]
    subject_name=sub
    mark_obtain=marks[subject_topper[i],i]
    print(f"Topper in {sub}: Student {student_index} with {mark_obtain} marks")


[12 28 48 38  7]
Topper in Math: Student 12 with 99 marks
Topper in Physics: Student 28 with 99 marks
Topper in Chemistry: Student 48 with 98 marks
Topper in Biology: Student 38 with 98 marks
Topper in English: Student 7 with 99 marks
